name: Frontend CI for JSP, HTML, and Tailwind

on:
  push:
    branches:
      - Development
      - QA
      - Regression
      - main
    paths:
      - '**/*.jsp'  # JSP files in any folder
      - '**/*.html' # HTML files
      - '**/*.css'  # CSS/Tailwind files
  pull_request:
    branches:
      - Development  # Added for completeness
      - QA
      - Regression
      - main
    paths:
      - '**/*.jsp'
      - '**/*.html'
      - '**/*.css'

jobs:
  ci-build:
    name: CI Build and Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js for Tailwind
        uses: actions/setup-node@v4
        with:
          node-version: '22.12.0'

      - name: Build Tailwind CSS
        run: npx tailwindcss -i ./src/main/webapp/css/input.css -o ./src/main/webapp/css/output.css --minify  # Adjust input/output paths to match your actual folder structure

      - name: Basic HTML/JSP Validation (Optional)
        run: |
          echo "Running basic checks on HTML/JSP files..."
          # Simple check - add tools if desired (e.g., tidy for HTML)
          sudo apt-get install -y tidy
          tidy -e src/main/webapp/**/*.html src/main/webapp/**/*.jsp || echo "Warnings found - check logs"

      - name: Upload CI Artifacts (Optional)
        uses: actions/upload-artifact@v4
        with:
          name: frontend-ci-assets
          path: src/main/webapp/css/  # Folder with built files; adjust as needed
