name: Frontend CI for JSP, HTML, and Tailwind

on:
  push:
    branches:
      - Development
      - QA
      - Regression
      - main
    paths:
      - '**/*.jsp'
      - '**/*.html'
  pull_request:
    branches:
      - Development
      - QA
      - Regression
      - main
    paths:
      - '**/*.jsp'
      - '**/*.html'

jobs:
  ci-build:
    name: CI Build and Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.12.0'

      - name: Basic HTML/JSP Validation (Optional)
        run: |
          echo "Running basic checks on HTML/JSP files..."
          sudo apt-get install -y tidy
          tidy -e src/main/webapp/**/*.html src/main/webapp/**/*.jsp || echo "Warnings found - check logs"
